image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false


# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: set up supporting services
    init: |
      # we use rabbit for our queue
      sudo service rabbitmq-server start
      # redis is our cache
      sudo service redis-server start
      gp sync-done backing-services

  - name: set up python dependencies and database
    init: |
      cp ./.env.gitpod ./.env
      mysqladmin create greencheck
      gp sync-await backing-services
      pipenv install --dev
    command: pipenv run ./manage.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
