image:
  file: .gitpod.dockerfile


# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: set up supporting services
    init: |
      # we use rabbit for our queue
      sudo service rabbitmq-server start
      # redis is our cache
      sudo service redis-server start
      gp sync-done backing-services

  - name: set up python dependencies and database
    init: |
      cp ./.env.gitpod ./.env
      gp sync-await backing-services
      pipenv install --dev
    command: pipenv run ./manage runserver

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
